version: '3.1'

services:
  php:
    build: ./docker/php
    links:
      - mongo
    volumes:
      - ./php-mongodb:/var/www/html
    ports:
      - 80:80
    working_dir: /var/www/html

  composer:
    build: ./docker/composer
    volumes:
      - ./php-mongodb:/app
    working_dir: /app
    user: 1000:1000
    tty: true

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
